lista_libros = [
    {"isbn": "978-1", "titulo": "Cien Años de Soledad", "precio": 25.0, "unidades_vendidas": 1500, "stock": 40, "genero_literario": "Ficción", "apellido_autor": "García Márquez", "porcentaje_autor": 0.15, "estado_impresion": "activo", "categoria": "Ficción"},
    {"isbn": "978-2", "titulo": "Cálculo de Una Variable", "precio": 50.0, "unidades_vendidas": 500, "stock": 20, "genero_literario": "Matemáticas", "apellido_autor": "Stewart", "porcentaje_autor": 0.10, "estado_impresion": "activo", "categoria": "Académico"},
    {"isbn": "978-3", "titulo": "Libro Viejo", "precio": 10.0, "unidades_vendidas": 5, "stock": 2, "genero_literario": "Historia", "apellido_autor": "Desconocido", "porcentaje_autor": 0.05, "estado_impresion": "descatalogado", "categoria": "Ficción"},
    {"isbn": "978-4", "titulo": "1984", "precio": 18.0, "unidades_vendidas": 2000, "stock": 50, "genero_literario": "Ficción", "apellido_autor": "Orwell", "porcentaje_autor": 0.12, "estado_impresion": "activo", "categoria": "Ficción"},
    {"isbn": "978-5", "titulo": "Python para Todos", "precio": 35.0, "unidades_vendidas": 1200, "stock": 100, "genero_literario": "Programación", "apellido_autor": "Severance", "porcentaje_autor": 0.20, "estado_impresion": "activo", "categoria": "Académico"},
    {"titulo": "Libro sin ISBN", "precio": 5.0, "unidades_vendidas": 0, "stock": 1, "genero_literario": "Varios", "apellido_autor": "N/A", "porcentaje_autor": 0.0, "estado_impresion": "activo", "categoria": "Ficción"},
    {"isbn": "978-7", "titulo": "Crónica de una Muerte Anunciada", "precio": 20.0, "unidades_vendidas": 800, "stock": 15, "genero_literario": "Ficción", "apellido_autor": "García Márquez", "porcentaje_autor": 0.15, "estado_impresion": "activo", "categoria": "Ficción"},
    {"isbn": "978-8", "titulo": "Introducción a la IA", "precio": 45.0, "unidades_vendidas": 300, "stock": 10, "genero_literario": "Programación", "apellido_autor": "Russell", "porcentaje_autor": 0.10, "estado_impresion": "activo", "categoria": "Académico"},
    {"isbn": "978-9", "titulo": "Don Quijote", "precio": 30.0, "unidades_vendidas": 400, "stock": 5, "genero_literario": "Ficción", "apellido_autor": "Cervantes", "porcentaje_autor": 0.10, "estado_impresion": "activo", "categoria": "Ficción"},
    {"isbn": "978-10", "titulo": "Anatomía Humana", "precio": 70.0, "unidades_vendidas": 100, "stock": 8, "genero_literario": "Medicina", "apellido_autor": "Netter", "porcentaje_autor": 0.15, "estado_impresion": "activo", "categoria": "Académico"}
]
